
DELETE [dbo].[tbl_User]
SET IDENTITY_INSERT [dbo].[tbl_User] ON
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (1, N'16df5b34-cff4-482f-8e51-fd645a8c084e', N'john', N'apeshi', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'douglas.wong@monash.edu', NULL, NULL, 0, NULL, NULL, NULL, N'douglasw', CAST(0x0000A1CF00DDF913 AS DateTime), N'douglasw', CAST(0x0000A1CF00DDF913 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (2, N'5d42a4f4-92af-496d-afdd-89c6baaa3631', N'test', N'test', N'3333333333333333', 1, N'3333333333333333', N'333333333333', N'3333333', N'33333', 3, N'3333', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, 0, N'admin', CAST(0x0000A1CF00E58684 AS DateTime), N'douglasw', CAST(0x0000A1CF00DFAA53 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (3, N'8153c24c-e396-46ef-96e8-978b38f38ebc', N'jj', N'jj', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'admin', CAST(0x0000A1CF00EAA391 AS DateTime), N'admin', CAST(0x0000A1CF00EAA391 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (4, N'f05412e4-414e-4db0-b20e-823193dece1a', N'Sally', N'Smithers', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'0395623366', 0, NULL, NULL, NULL, N'admin', CAST(0x0000A1CF00F74256 AS DateTime), N'admin', CAST(0x0000A1CF00F74256 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (5, N'fba38401-0b46-48b3-9819-9a1363d78e0c', N'George', N'Brown', NULL, 2, N'3265555554441111', N'Kew Medical Centre', N'102 Kew Street', N'Kew', 2, N'3122', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, 1, N'admin', CAST(0x0000A1CF01021414 AS DateTime), N'admin', CAST(0x0000A1CF01021414 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (6, N'6e9ae488-a6fe-4973-9f8a-e8ce846ea5ef', N'Sue', N'Evan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'03283438822', 0, NULL, NULL, NULL, N'cidmu', CAST(0x0000A1D200D96224 AS DateTime), N'cidmu', CAST(0x0000A1D200D96224 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (7, N'6c157804-559c-4443-a214-5e11d8c2770c', N'bdr', N'data', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'cidmu', CAST(0x0000A1D200FAB6B5 AS DateTime), N'cidmu', CAST(0x0000A1D200FAB6B5 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (8, N'ddc49b5d-eb79-4679-b65a-c338b88b30ab', N'George', N'Brown', NULL, 2, N'3265555554441111', N'Kew Medical Centre', N'102 Kew Street', N'Kew', 2, N'3122', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, 1, N'admin', CAST(0x0000A1CF01021414 AS DateTime), N'admin', CAST(0x0000A1CF01021414 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (9, N'd76fcbb4-d44f-4fb4-a1e9-5bf7b9605ced', N'Sue', N'Evan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'03283438822', 0, NULL, NULL, NULL, N'cidmu', CAST(0x0000A1D200D96224 AS DateTime), N'cidmu', CAST(0x0000A1D200D96224 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (10, N'2d0a0afa-4630-4e93-8eb8-ebf28ab800f4', N'bdr', N'data', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'cidmu', CAST(0x0000A1D200FAB6B5 AS DateTime), N'cidmu', CAST(0x0000A1D200FAB6B5 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (11, N'1be41b87-6da1-4c05-884d-ca4a77ea68c1', N'George', N'Brown', NULL, 2, N'3265555554441111', N'Kew Medical Centre', N'102 Kew Street', N'Kew', 2, N'3122', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, 1, N'admin', CAST(0x0000A1CF01021414 AS DateTime), N'admin', CAST(0x0000A1CF01021414 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (12, N'ced18899-6781-4690-acce-740864143ac1', N'Sue', N'Evan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'03283438822', 0, NULL, NULL, NULL, N'cidmu', CAST(0x0000A1D200D96224 AS DateTime), N'cidmu', CAST(0x0000A1D200D96224 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (13, N'c1c25ad2-508a-4b74-b9e4-d239fd9460d6', N'bdr', N'data', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'cidmu', CAST(0x0000A1D200FAB6B5 AS DateTime), N'cidmu', CAST(0x0000A1D200FAB6B5 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (14, N'14a23d70-2b22-4033-addf-89d0aec8c142', N'George', N'Brown', NULL, 2, N'3265555554441111', N'Kew Medical Centre', N'102 Kew Street', N'Kew', 2, N'3122', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, 1, N'admin', CAST(0x0000A1CF01021414 AS DateTime), N'admin', CAST(0x0000A1CF01021414 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (15, N'26182f52-5af3-4c8a-94b6-12fe5be551c9', N'Sue', N'Evan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'03283438822', 0, NULL, NULL, NULL, N'cidmu', CAST(0x0000A1D200D96224 AS DateTime), N'cidmu', CAST(0x0000A1D200D96224 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (16, N'7e29b1f5-a8f8-48b1-8a4a-6f5a4bfaca0b', N'bdr', N'data', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, N'cidmu', CAST(0x0000A1D200FAB6B5 AS DateTime), N'cidmu', CAST(0x0000A1D200FAB6B5 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (17, N'599ba0d5-4cea-4db7-8c1f-3a5941234334', N'George', N'Brown', NULL, 2, N'3265555554441111', N'Kew Medical Centre', N'102 Kew Street', N'Kew', 2, N'3122', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, 1, N'admin', CAST(0x0000A1CF01021414 AS DateTime), N'admin', CAST(0x0000A1CF01021414 AS DateTime))
INSERT [dbo].[tbl_User] ([UserId], [UId], [UserGivenName], [UserFamilyName], [HPII], [SpecialityId], [AHPRARegNo], [PrimaryPracticeName], [PrimaryPracticeAddress], [PrimaryPracticeSuburb], [PrimaryPracticeStateId], [PrimaryPracticePostcode], [SecondaryPracticeName], [SecondaryPracticeAddress], [SecondaryPracticeSuburb], [SecondaryPracticeStateId], [SecondaryPracticePostcode], [UserSecondaryEmail], [WorkPhone], [Mobile], [NoSystemNotificationEmail], [Fax], [SurgeonReportId], [ConsentId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (18, N'19f52951-9351-4d2a-a4b2-a77d77afdde7', N'Sue', N'Evan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'03283438822', 0, NULL, NULL, NULL, N'cidmu', CAST(0x0000A1D200D96224 AS DateTime), N'cidmu', CAST(0x0000A1D200D96224 AS DateTime))

SET IDENTITY_INSERT [dbo].[tbl_User] OFF

DELETE [dbo].[tbl_Site]
SET IDENTITY_INSERT [dbo].[tbl_Site] ON
INSERT [dbo].[tbl_Site] ([SiteId], [SiteRoleName], [HPIO], [SiteName], [SITEPI], [SitePrincipalPhone], [SiteDataManager], [SiteDataManagerPhone], [SiteDataCollector], [SiteDataCollectorPhone], [SiteStreet], [SiteSuburb], [SiteStateId], [SitePostcode], [SiteTypeId], [SiteStatusId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedByDateTime]) VALUES (1, N'S_1', N'3333333333333333', N'Alfred', N'Bing', NULL, NULL, NULL, NULL, NULL, N'aaa', N'prahran', 1, N'3333', 2, 1, N'cidmu', CAST(0x0000A1D300AE3488 AS DateTime), NULL, NULL)
INSERT [dbo].[tbl_Site] ([SiteId], [SiteRoleName], [HPIO], [SiteName], [SITEPI], [SitePrincipalPhone], [SiteDataManager], [SiteDataManagerPhone], [SiteDataCollector], [SiteDataCollectorPhone], [SiteStreet], [SiteSuburb], [SiteStateId], [SitePostcode], [SiteTypeId], [SiteStatusId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedByDateTime]) VALUES (2, N'S_2', N'3333333333333333', N'Alfred Campus 2', N'Alfred', NULL, NULL, NULL, NULL, NULL, N'aa', N'aa', 7, N'3333', 3, 1, N'admin', CAST(0x0000A1CF00E561EA AS DateTime), NULL, NULL)
INSERT [dbo].[tbl_Site] ([SiteId], [SiteRoleName], [HPIO], [SiteName], [SITEPI], [SitePrincipalPhone], [SiteDataManager], [SiteDataManagerPhone], [SiteDataCollector], [SiteDataCollectorPhone], [SiteStreet], [SiteSuburb], [SiteStateId], [SitePostcode], [SiteTypeId], [SiteStatusId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedByDateTime]) VALUES (3, N'S_3', N'3265699999999993', N'Kew Plastic Surgery', N'Suzy Jones', N'0395699999', NULL, NULL, NULL, NULL, N'102 Polo Street', N'Appleton', 1, N'3202', 2, 1, NULL, CAST(0x0000A1CF00EE9FC7 AS DateTime), N'admin', CAST(0x0000A1CF00EE9FC7 AS DateTime))
INSERT [dbo].[tbl_Site] ([SiteId], [SiteRoleName], [HPIO], [SiteName], [SITEPI], [SitePrincipalPhone], [SiteDataManager], [SiteDataManagerPhone], [SiteDataCollector], [SiteDataCollectorPhone], [SiteStreet], [SiteSuburb], [SiteStateId], [SitePostcode], [SiteTypeId], [SiteStatusId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedByDateTime]) VALUES (4, N'S_4', N'9588877888888883', N'Betty Day Surgery', N'Fred Smith', NULL, NULL, NULL, NULL, NULL, N'21 The Way', N'Kew', 2, N'3100', 4, 1, NULL, CAST(0x0000A1CF00EEFCED AS DateTime), N'admin', CAST(0x0000A1CF00EEFCED AS DateTime))
INSERT [dbo].[tbl_Site] ([SiteId], [SiteRoleName], [HPIO], [SiteName], [SITEPI], [SitePrincipalPhone], [SiteDataManager], [SiteDataManagerPhone], [SiteDataCollector], [SiteDataCollectorPhone], [SiteStreet], [SiteSuburb], [SiteStateId], [SitePostcode], [SiteTypeId], [SiteStatusId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedByDateTime]) VALUES (5, N'S_5', N'4388299933438834', N'The Clinic', N'Fred Smith', N'03982288888', N'Fred Jones', N'39994000033', N'Sue Smith', NULL, N'203 The Alencue', N'Kew', 3, N'2333', 2, 1, NULL, CAST(0x0000A1D200D8AD23 AS DateTime), N'cidmu', CAST(0x0000A1D200D8AD23 AS DateTime))
SET IDENTITY_INSERT [dbo].[tbl_Site] OFF

DELETE dbo.tbl_Patient
SET IDENTITY_INSERT [dbo].[tbl_Patient] ON
INSERT [dbo].[tbl_Patient] ([PatientId], [IHI], [GivenName], [MiddleName], [FamilyName], [RecentFormerName], [FormerName], [DOB], [GenderId], [MedicareNo], [NoMedicareNo], [Street], [Suburb], [StateId], [Postcode], [NoAusPostcode], [AddressNotKnown], [NoFixedAddress], [Email], [HomePhone], [WorkPhone], [Mobile], [NoPhoneNo], [PreferredLanguageId], [HealthStatusId], [DOD], [AgeAtDeath], [CauseOfDeathId], [DateConsentLetterSent], [ConsentId], [OptOutDate], [OptOutReasonId], [OptOutReasonOther], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (1, NULL, N'Suzy', N'Apple', N'Jones', N'', NULL, CAST(0x05E00A00 AS Date), 2, NULL, 1, N'128 Candy Way', N'Kew', 1, N'2101', 0, 0, 0, NULL, N'0298569999', N'0460398765', NULL, 0, 1201, 0, NULL, NULL, NULL, NULL, 2, NULL, NULL, N'', N'joshis', CAST(0x0000A1D200C08F92 AS DateTime), N'admin', CAST(0x0000A1CF00EB6A17 AS DateTime))
INSERT [dbo].[tbl_Patient] ([PatientId], [IHI], [GivenName], [MiddleName], [FamilyName], [RecentFormerName], [FormerName], [DOB], [GenderId], [MedicareNo], [NoMedicareNo], [Street], [Suburb], [StateId], [Postcode], [NoAusPostcode], [AddressNotKnown], [NoFixedAddress], [Email], [HomePhone], [WorkPhone], [Mobile], [NoPhoneNo], [PreferredLanguageId], [HealthStatusId], [DOD], [AgeAtDeath], [CauseOfDeathId], [DateConsentLetterSent], [ConsentId], [OptOutDate], [OptOutReasonId], [OptOutReasonOther], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (2, NULL, N'Maddie', NULL, N'Smith', N'', NULL, CAST(0x5FE50A00 AS Date), 2, N'21366666663', 0, N'158', N'The Gap', 2, N'3122', 0, 0, 0, NULL, N'0232655555', NULL, NULL, 0, 1201, 0, NULL,NULL, NULL, NULL, 2, NULL, NULL, N'', N'admin', CAST(0x0000A1CF00ECCA2A AS DateTime), N'admin', CAST(0x0000A1CF00ECCA2A AS DateTime))
INSERT [dbo].[tbl_Patient] ([PatientId], [IHI], [GivenName], [MiddleName], [FamilyName], [RecentFormerName], [FormerName], [DOB], [GenderId], [MedicareNo], [NoMedicareNo], [Street], [Suburb], [StateId], [Postcode], [NoAusPostcode], [AddressNotKnown], [NoFixedAddress], [Email], [HomePhone], [WorkPhone], [Mobile], [NoPhoneNo], [PreferredLanguageId], [HealthStatusId], [DOD], [AgeAtDeath], [CauseOfDeathId], [DateConsentLetterSent], [ConsentId], [OptOutDate], [OptOutReasonId], [OptOutReasonOther], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (3, NULL, N'Rita', N'Jo', N'Raymond', N'', NULL, CAST(0x4A260B00 AS Date),2, N'32659988555', 0, N'189 Hoddle Street', N'Collingwood', 2, N'3101', 0, 0, 0, NULL, N'0395869999', NULL, NULL, 0, 1201, 0, NULL, NULL, NULL, NULL, 2, NULL, NULL, N'', N'admin', CAST(0x0000A1CF01067B1E AS DateTime), N'admin', CAST(0x0000A1CF010672A9 AS DateTime))
INSERT [dbo].[tbl_Patient] ([PatientId], [IHI], [GivenName], [MiddleName], [FamilyName], [RecentFormerName], [FormerName], [DOB], [GenderId], [MedicareNo], [NoMedicareNo], [Street], [Suburb], [StateId], [Postcode], [NoAusPostcode], [AddressNotKnown], [NoFixedAddress], [Email], [HomePhone], [WorkPhone], [Mobile], [NoPhoneNo], [PreferredLanguageId], [HealthStatusId], [DOD], [AgeAtDeath], [CauseOfDeathId], [DateConsentLetterSent], [ConsentId], [OptOutDate], [OptOutReasonId], [OptOutReasonOther], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (4, NULL, N'Tracey', NULL, N'Wilson', N'Ruth', NULL, CAST(0x42240B00 AS Date), 2, N'12036666666', 0, N'158 Yarra Street', N'Abbotsford', 2, N'3223', 0, 0, 0, N'tracey@gmail.com', N'0395999888', NULL, NULL, 0, 1201, 0, NULL, NULL, NULL, NULL, 2, NULL, NULL, N'', N'admin', CAST(0x0000A1CF010790D6 AS DateTime), N'admin', CAST(0x0000A1CF010790D6 AS DateTime))
INSERT [dbo].[tbl_Patient] ([PatientId], [IHI], [GivenName], [MiddleName], [FamilyName], [RecentFormerName], [FormerName], [DOB], [GenderId], [MedicareNo], [NoMedicareNo], [Street], [Suburb], [StateId], [Postcode], [NoAusPostcode], [AddressNotKnown], [NoFixedAddress], [Email], [HomePhone], [WorkPhone], [Mobile], [NoPhoneNo], [PreferredLanguageId], [HealthStatusId], [DOD], [AgeAtDeath], [CauseOfDeathId], [DateConsentLetterSent], [ConsentId], [OptOutDate], [OptOutReasonId], [OptOutReasonOther], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (5, NULL, N'Carol', N'Pip', N'Drummond', N'', NULL, CAST(0x5FE50A00 AS Date), 2, N'23336666666', 0, NULL, NULL, NULL, NULL, 0, 1, 0, NULL, NULL, NULL, NULL, 1, NULL, 1, CAST(0x19370B00 AS Date), NULL, -1, NULL, 2, NULL, NULL, N'', N'admin', CAST(0x0000A1CF010C58B4 AS DateTime), N'admin', CAST(0x0000A1CF010C58B4 AS DateTime))
INSERT [dbo].[tbl_Patient] ([PatientId], [IHI], [GivenName], [MiddleName], [FamilyName], [RecentFormerName], [FormerName], [DOB], [GenderId], [MedicareNo], [NoMedicareNo], [Street], [Suburb], [StateId], [Postcode], [NoAusPostcode], [AddressNotKnown], [NoFixedAddress], [Email], [HomePhone], [WorkPhone], [Mobile], [NoPhoneNo], [PreferredLanguageId], [HealthStatusId], [DOD], [AgeAtDeath], [CauseOfDeathId], [DateConsentLetterSent], [ConsentId], [OptOutDate], [OptOutReasonId], [OptOutReasonOther], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (6, NULL, N'Suzy', NULL, N'Jones', N'', NULL, CAST(0x05E00A00 AS Date), 2, NULL, 1, N'23 Jones', N'Kew', 2, N'3211', 0, 0, 0, NULL, N'03293994333', NULL, NULL, 0, 1201, 0, NULL, NULL,  NULL, NULL, 2, NULL, NULL, N'', N'cidmu', CAST(0x0000A1D200DED4CA AS DateTime), N'cidmu', CAST(0x0000A1D200DED4CA AS DateTime))
INSERT [dbo].[tbl_Patient] ([PatientId], [IHI], [GivenName], [MiddleName], [FamilyName], [RecentFormerName], [FormerName], [DOB], [GenderId], [MedicareNo], [NoMedicareNo], [Street], [Suburb], [StateId], [Postcode], [NoAusPostcode], [AddressNotKnown], [NoFixedAddress], [Email], [HomePhone], [WorkPhone], [Mobile], [NoPhoneNo], [PreferredLanguageId], [HealthStatusId], [DOD], [AgeAtDeath], [CauseOfDeathId], [DateConsentLetterSent], [ConsentId], [OptOutDate], [OptOutReasonId], [OptOutReasonOther], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (7, NULL, N'Jo', NULL, N'Blo', N'', NULL, CAST(0x07130B00 AS Date), 2, NULL, 1, NULL, NULL, NULL, NULL, 0, 1, 0, NULL, NULL, NULL, NULL, 1, 1201, 0, NULL, NULL, NULL, NULL, 2, NULL, NULL, N'', N'cidmu', CAST(0x0000A1D200DFBA76 AS DateTime), N'cidmu', CAST(0x0000A1D200DFBA76 AS DateTime))
INSERT [dbo].[tbl_Patient] ([PatientId], [IHI], [GivenName], [MiddleName], [FamilyName], [RecentFormerName], [FormerName], [DOB], [GenderId], [MedicareNo], [NoMedicareNo], [Street], [Suburb], [StateId], [Postcode], [NoAusPostcode], [AddressNotKnown], [NoFixedAddress], [Email], [HomePhone], [WorkPhone], [Mobile], [NoPhoneNo], [PreferredLanguageId], [HealthStatusId], [DOD], [AgeAtDeath], [CauseOfDeathId], [DateConsentLetterSent], [ConsentId], [OptOutDate], [OptOutReasonId], [OptOutReasonOther], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (8, NULL, N'Suzy', NULL, N'Smith', N'', NULL, CAST(0x07240B00 AS Date), 2, NULL, 1, NULL, NULL, NULL, NULL, 0, 1, 0, NULL, NULL, NULL, NULL, 1, 1201, 0, NULL, NULL, NULL, NULL, 2, NULL, NULL, N'', N'cidmu', CAST(0x0000A1D300AFA004 AS DateTime), N'cidmu', CAST(0x0000A1D300AFA004 AS DateTime))
SET IDENTITY_INSERT [dbo].[tbl_Patient] OFF


 
 
  DELETE dbo.tbl_Device
 SET IDENTITY_INSERT [dbo].[tbl_Device] ON
 
 INSERT [dbo].[tbl_Device] ([DeviceId], [DeviceReferenceNo]) VALUES (-1, N'Other')
 
INSERT [dbo].[tbl_Device] ([DeviceId], [DeviceReferenceNo], [DeviceManufacturerId], [DeviceDistributorId], [DeviceTypeId], [DeviceShellId], [DeviceFillId], [DeviceShapeId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (1, N'N-27', 2, 2, 1, 1, 1, 1, N'cidmu', CAST(0x0000A1D300E4394A AS DateTime), N'cidmu', CAST(0x0000A1D300E4394A AS DateTime))
INSERT [dbo].[tbl_Device] ([DeviceId], [DeviceReferenceNo], [DeviceManufacturerId], [DeviceDistributorId], [DeviceTypeId], [DeviceShellId], [DeviceFillId], [DeviceShapeId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (2, N'N-67', 1, 1, 2, 2, 2, 2, N'cidmu', CAST(0x0000A1D300E45462 AS DateTime), N'cidmu', CAST(0x0000A1D300E45462 AS DateTime))
SET IDENTITY_INSERT [dbo].[tbl_Device] OFF
 
 
 DELETE dbo.tbl_PatientOperation
 SET IDENTITY_INSERT [dbo].[tbl_PatientOperation] ON
--INSERT [dbo].[tbl_PatientOperation] ([PatientOperationId], [PatientId], [PatientUR], [OperationDate], [OperationDateAccuracyId], [BreastId], [OperationCode1], [OperationCode2], [OperationCode3], [OperationCode4], [DiagnosisCode1], [DiagnosisCode2], [DiagnosisCode3], [DiagnosisCode4], [SiteId], [UserId], [AdministeredProphylacticAntibiotics], [AntibioticDippingSolution], [AnitsepticRinse], [GloveChangeInsertion], [SleeveFunnel], [DrainsUsed], [NotKnown], [NotStated], [DischargeDate], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (2, 2, 21, CAST(0x2E370B00 AS Date), NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'hton', CAST(0x0000A1D300000000 AS DateTime), N'hton', CAST(0x0000A1D300000000 AS DateTime))
--INSERT [dbo].[tbl_PatientOperation] ([PatientOperationId], [PatientId], [PatientUR], [OperationDate], [OperationDateAccuracyId], [BreastId], [OperationCode1], [OperationCode2], [OperationCode3], [OperationCode4], [DiagnosisCode1], [DiagnosisCode2], [DiagnosisCode3], [DiagnosisCode4], [SiteId], [UserId], [AdministeredProphylacticAntibiotics], [AntibioticDippingSolution], [AnitsepticRinse], [GloveChangeInsertion], [SleeveFunnel], [DrainsUsed], [NotKnown], [NotStated], [DischargeDate], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (1, 1, 1, CAST(0x2E370B00 AS Date), NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'hton', CAST(0x0000A1D300000000 AS DateTime), N'hton', CAST(0x0000A1D300000000 AS DateTime))
SET IDENTITY_INSERT [dbo].[tbl_PatientOperation] OFF

 DELETE dbo.tbl_PatientOperationBSideDtls
 SET IDENTITY_INSERT [dbo].[tbl_PatientOperationBSideDtls] ON
--INSERT [dbo].[tbl_PatientOperationBSideDtls] ([PatientOperationBSideId], [PatientOperationId], [BreastSideId], [ReasonOperationId], [DeviceOperationId], [OperationTypeId], [PreviousRadiotheraphyId], [DeviceId], [DeviceLotNo], [DeviceSerialNo], [ReferenceNoOther], [ManufacturerOther], [ShellOther], [FillOther], [ShapeOther], [OperationTypePrimaryId], [RevisionTypeId], [CapsulectomyId], [ReasonRevisionId], [RemovingPIPImplantId], [RemovingImplantOverseaId], [DeviceRuptureId], [SiliconExtravasationId], [DeviceDeflationId], [CapsularContractureId], [DeviceMalpositionId], [SkinScarringProblemsId], [DeepWoundInfectionId], [SeromaHaematomaId], [BreastCancerId], [AnapLargeCelLymphomaId], [IncisionSiteId], [IncisionOther], [PlaneId], [MastopexyId], [FlapCoverId], [MeshDermalSheetId], [FatGraftingId], [IfTissueExpander], [RevisionSectionOther], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (1, 1, 1, 1, 1, 1, NULL, 2, NULL, N'12334', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, N'hton', CAST(0x0000A1D300000000 AS DateTime), N'hton', CAST(0x0000A1D300000000 AS DateTime))
--INSERT [dbo].[tbl_PatientOperationBSideDtls] ([PatientOperationBSideId], [PatientOperationId], [BreastSideId], [ReasonOperationId], [DeviceOperationId], [OperationTypeId], [PreviousRadiotheraphyId], [DeviceId], [DeviceLotNo], [DeviceSerialNo], [ReferenceNoOther], [ManufacturerOther], [ShellOther], [FillOther], [ShapeOther], [OperationTypePrimaryId], [RevisionTypeId], [CapsulectomyId], [ReasonRevisionId], [RemovingPIPImplantId], [RemovingImplantOverseaId], [DeviceRuptureId], [SiliconExtravasationId], [DeviceDeflationId], [CapsularContractureId], [DeviceMalpositionId], [SkinScarringProblemsId], [DeepWoundInfectionId], [SeromaHaematomaId], [BreastCancerId], [AnapLargeCelLymphomaId], [IncisionSiteId], [IncisionOther], [PlaneId], [MastopexyId], [FlapCoverId], [MeshDermalSheetId], [FatGraftingId], [IfTissueExpander], [RevisionSectionOther], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (2, 1, 2, 1, 1, 1, NULL, NULL, NULL, N'12334', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, N'hton', CAST(0x0000A1D300000000 AS DateTime), N'hton', CAST(0x0000A1D300000000 AS DateTime))
--INSERT [dbo].[tbl_PatientOperationBSideDtls] ([PatientOperationBSideId], [PatientOperationId], [BreastSideId], [ReasonOperationId], [DeviceOperationId], [OperationTypeId], [PreviousRadiotheraphyId], [DeviceId], [DeviceLotNo], [DeviceSerialNo], [ReferenceNoOther], [ManufacturerOther], [ShellOther], [FillOther], [ShapeOther], [OperationTypePrimaryId], [RevisionTypeId], [CapsulectomyId], [ReasonRevisionId], [RemovingPIPImplantId], [RemovingImplantOverseaId], [DeviceRuptureId], [SiliconExtravasationId], [DeviceDeflationId], [CapsularContractureId], [DeviceMalpositionId], [SkinScarringProblemsId], [DeepWoundInfectionId], [SeromaHaematomaId], [BreastCancerId], [AnapLargeCelLymphomaId], [IncisionSiteId], [IncisionOther], [PlaneId], [MastopexyId], [FlapCoverId], [MeshDermalSheetId], [FatGraftingId], [IfTissueExpander], [RevisionSectionOther], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (3, 2, 1, 1, 2, 2, NULL, 2, NULL, N'12334', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'hton', CAST(0x0000A1D300000000 AS DateTime), N'hton', CAST(0x0000A1D300000000 AS DateTime))
SET IDENTITY_INSERT [dbo].[tbl_PatientOperationBSideDtls] OFF





/****** Object:  Table [dbo].[tbl_Device]    Script Date: 06/10/2013 10:25:21 ******/
--SET IDENTITY_INSERT [dbo].[tbl_Device] ON
--INSERT [dbo].[tbl_Device] ([DeviceId], [DeviceReferenceNo], [DeviceManufacturerId], [DeviceDistributorId], [DeviceTypeId], [DeviceShellId], [DeviceFillId], [DeviceShapeId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (1, N'N-27', 2, 2, 1, 1, 1, 1, N'cidmu', CAST(0x0000A1D300E4394A AS DateTime), N'cidmu', CAST(0x0000A1D300E4394A AS DateTime))
--INSERT [dbo].[tbl_Device] ([DeviceId], [DeviceReferenceNo], [DeviceManufacturerId], [DeviceDistributorId], [DeviceTypeId], [DeviceShellId], [DeviceFillId], [DeviceShapeId], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime]) VALUES (2, N'N-67', 1, 1, 2, 2, 2, 2, N'cidmu', CAST(0x0000A1D300E45462 AS DateTime), N'cidmu', CAST(0x0000A1D300E45462 AS DateTime))
--SET IDENTITY_INSERT [dbo].[tbl_Device] OFF
/****** Object:  Table [dbo].[tbl_PatientOperation]    Script Date: 06/10/2013 10:25:21 ******/
--SET IDENTITY_INSERT [dbo].[tbl_PatientOperation] ON
--INSERT [dbo].[tbl_PatientOperation] ([PatientOperationId], [PatientId], [PatientUR], [OperationDate], [OperationDateAccuracyId], [BreastId], [OperationCode1], [OperationCode2], [OperationCode3], [OperationCode4], [DiagnosisCode1], [DiagnosisCode2], [DiagnosisCode3], [DiagnosisCode4], [SiteId], [UserId], [NippleGuard], [AdministeredProphylacticAntibiotics], [AntibioticDippingSolution], [AnitsepticRinse], [GloveChangeInsertion], [SleeveFunnel], [DrainsUsed], [NotKnown], [NotStated], [DischargeDate], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime], [Validated]) VALUES (1, 1, N'1', CAST(0x2E370B00 AS Date), 1, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, CAST(0x2C370B00 AS Date), N'douglasw', CAST(0x0000A1D6011D33FA AS DateTime), N'hton', CAST(0x0000A1D300000000 AS DateTime), NULL)
--INSERT [dbo].[tbl_PatientOperation] ([PatientOperationId], [PatientId], [PatientUR], [OperationDate], [OperationDateAccuracyId], [BreastId], [OperationCode1], [OperationCode2], [OperationCode3], [OperationCode4], [DiagnosisCode1], [DiagnosisCode2], [DiagnosisCode3], [DiagnosisCode4], [SiteId], [UserId], [NippleGuard], [AdministeredProphylacticAntibiotics], [AntibioticDippingSolution], [AnitsepticRinse], [GloveChangeInsertion], [SleeveFunnel], [DrainsUsed], [NotKnown], [NotStated], [DischargeDate], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime], [Validated]) VALUES (2, 2, N'21', CAST(0x2E370B00 AS Date), NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'hton', CAST(0x0000A1D300000000 AS DateTime), N'hton', CAST(0x0000A1D300000000 AS DateTime), NULL)
--INSERT [dbo].[tbl_PatientOperation] ([PatientOperationId], [PatientId], [PatientUR], [OperationDate], [OperationDateAccuracyId], [BreastId], [OperationCode1], [OperationCode2], [OperationCode3], [OperationCode4], [DiagnosisCode1], [DiagnosisCode2], [DiagnosisCode3], [DiagnosisCode4], [SiteId], [UserId], [NippleGuard], [AdministeredProphylacticAntibiotics], [AntibioticDippingSolution], [AnitsepticRinse], [GloveChangeInsertion], [SleeveFunnel], [DrainsUsed], [NotKnown], [NotStated], [DischargeDate], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime], [Validated]) VALUES (5, 1, N'asd', CAST(0x2C370B00 AS Date), 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x0000A1D60104EC60 AS DateTime), N'cidmu', CAST(0x0000A1D60104EC60 AS DateTime), NULL)
--SET IDENTITY_INSERT [dbo].[tbl_PatientOperation] OFF
/****** Object:  Table [dbo].[tbl_PatientOperationBSideDtls]    Script Date: 06/10/2013 10:25:21 ******/
--SET IDENTITY_INSERT [dbo].[tbl_PatientOperationBSideDtls] ON
--INSERT [dbo].[tbl_PatientOperationBSideDtls] ([PatientOperationBSideId], [PatientOperationId], [BreastSideId], [ReasonOperationId], [DeviceOperationId], [OperationTypeId], [PreviousRadiotheraphyId], [DeviceId], [DeviceLotNo], [DeviceSerialNo], [ReferenceNoOther], [ManufacturerOther], [ShellOther], [FillOther], [ShapeOther], [OperationTypePrimaryId], [RevisionTypeId], [CapsulectomyId], [ReasonRevisionId], [RemovingPIPImplantId], [RemovingImplantOverseaId], [DeviceRuptureId], [SiliconExtravasationId], [DeviceDeflationId], [CapsularContractureId], [DeviceMalpositionId], [SkinScarringProblemsId], [DeepWoundInfectionId], [SeromaHaematomaId], [BreastCancerId], [AnapLargeCelLymphomaId], [RevisionSectionOther], [IncisionSiteId], [IncisionOther], [PlaneId], [MastopexyId], [FlapCoverId], [MeshDermalSheetId], [FatGraftingId], [IfTissueExpander], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime], [Validated]) VALUES (1, 1, 1, 1, 1, 1, 0, 2, N'234', N'12334', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 1, NULL, NULL, NULL, NULL, NULL, N'douglasw', CAST(0x0000A1D601250E56 AS DateTime), N'hton', CAST(0x0000A1D300000000 AS DateTime), 0)
--INSERT [dbo].[tbl_PatientOperationBSideDtls] ([PatientOperationBSideId], [PatientOperationId], [BreastSideId], [ReasonOperationId], [DeviceOperationId], [OperationTypeId], [PreviousRadiotheraphyId], [DeviceId], [DeviceLotNo], [DeviceSerialNo], [ReferenceNoOther], [ManufacturerOther], [ShellOther], [FillOther], [ShapeOther], [OperationTypePrimaryId], [RevisionTypeId], [CapsulectomyId], [ReasonRevisionId], [RemovingPIPImplantId], [RemovingImplantOverseaId], [DeviceRuptureId], [SiliconExtravasationId], [DeviceDeflationId], [CapsularContractureId], [DeviceMalpositionId], [SkinScarringProblemsId], [DeepWoundInfectionId], [SeromaHaematomaId], [BreastCancerId], [AnapLargeCelLymphomaId], [RevisionSectionOther], [IncisionSiteId], [IncisionOther], [PlaneId], [MastopexyId], [FlapCoverId], [MeshDermalSheetId], [FatGraftingId], [IfTissueExpander], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime], [Validated]) VALUES (2, 1, 2, 1, 1, 1, 0, 1, N'424', N'12334', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 1, NULL, NULL, NULL, NULL, NULL, N'douglasw', CAST(0x0000A1D601250E6A AS DateTime), N'hton', CAST(0x0000A1D300000000 AS DateTime), 0)
--INSERT [dbo].[tbl_PatientOperationBSideDtls] ([PatientOperationBSideId], [PatientOperationId], [BreastSideId], [ReasonOperationId], [DeviceOperationId], [OperationTypeId], [PreviousRadiotheraphyId], [DeviceId], [DeviceLotNo], [DeviceSerialNo], [ReferenceNoOther], [ManufacturerOther], [ShellOther], [FillOther], [ShapeOther], [OperationTypePrimaryId], [RevisionTypeId], [CapsulectomyId], [ReasonRevisionId], [RemovingPIPImplantId], [RemovingImplantOverseaId], [DeviceRuptureId], [SiliconExtravasationId], [DeviceDeflationId], [CapsularContractureId], [DeviceMalpositionId], [SkinScarringProblemsId], [DeepWoundInfectionId], [SeromaHaematomaId], [BreastCancerId], [AnapLargeCelLymphomaId], [RevisionSectionOther], [IncisionSiteId], [IncisionOther], [PlaneId], [MastopexyId], [FlapCoverId], [MeshDermalSheetId], [FatGraftingId], [IfTissueExpander], [LastUpdatedBy], [LastUpdatedDateTime], [CreatedBy], [CreatedDateTime], [Validated]) VALUES (3, 2, 1, 1, 2, 2, NULL, 2, NULL, N'12334', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'hton', CAST(0x0000A1D300000000 AS DateTime), N'hton', CAST(0x0000A1D300000000 AS DateTime), NULL)
--SET IDENTITY_INSERT [dbo].[tbl_PatientOperationBSideDtls] OFF
