//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.UI.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        public static string PatientHomePagePath;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.UI.Web.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abnormal.
        /// </summary>
        internal static string Abnormal {
            get {
                return ResourceManager.GetString("Abnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login attempt was not successful. Please try again..
        /// </summary>
        internal static string AccountLoginAttemptFailed {
            get {
                return ResourceManager.GetString("AccountLoginAttemptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login attempt was not successful. Please contact system administrator..
        /// </summary>
        internal static string AccountLoginAttemptFailed2 {
            get {
                return ResourceManager.GetString("AccountLoginAttemptFailed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Account.
        /// </summary>
        internal static string AccountRequestEmailSubject {
            get {
                return ResourceManager.GetString("AccountRequestEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/AddNewPatient.aspx.
        /// </summary>
        internal static string AddNewPatientPagePath {
            get {
                return ResourceManager.GetString("AddNewPatientPagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string AddNewPatientStatusDefault {
            get {
                return ResourceManager.GetString("AddNewPatientStatusDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/AdjuvantADTTherapy.aspx.
        /// </summary>
        internal static string AdjuvantADTTherapyPage {
            get {
                return ResourceManager.GetString("AdjuvantADTTherapyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/Brachytherapy.aspx.
        /// </summary>
        internal static string BrachyPage {
            get {
                return ResourceManager.GetString("BrachyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/Chemotherapy.aspx.
        /// </summary>
        internal static string ChemotherapyPage {
            get {
                return ResourceManager.GetString("ChemotherapyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/Chemotherapy.aspx.
        /// </summary>
        internal static string ChemotherapyPagePath {
            get {
                return ResourceManager.GetString("ChemotherapyPagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Admin/Clinician.aspx.
        /// </summary>
        internal static string ClinicianEditPath {
            get {
                return ResourceManager.GetString("ClinicianEditPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/Comorbidities.aspx.
        /// </summary>
        internal static string ComorbiditiesPage {
            get {
                return ResourceManager.GetString("ComorbiditiesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/Demographic.aspx.
        /// </summary>
        internal static string Demographic {
            get {
                return ResourceManager.GetString("Demographic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected.
        /// </summary>
        internal static string Detected {
            get {
                return ResourceManager.GetString("Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/Diagnosis.aspx.
        /// </summary>
        internal static string DiagnosisEditPagePath {
            get {
                return ResourceManager.GetString("DiagnosisEditPagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/DiagnosisHome.aspx.
        /// </summary>
        internal static string DiagnosisHomePagePath {
            get {
                return ResourceManager.GetString("DiagnosisHomePagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVA.
        /// </summary>
        internal static string DVA {
            get {
                return ResourceManager.GetString("DVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/FollowUp.aspx.
        /// </summary>
        internal static string FollowUpPagePath {
            get {
                return ResourceManager.GetString("FollowUpPagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/Hifu.aspx.
        /// </summary>
        internal static string HifuPage {
            get {
                return ResourceManager.GetString("HifuPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Admin/Institute.aspx.
        /// </summary>
        internal static string InstituteEditPath {
            get {
                return ResourceManager.GetString("InstituteEditPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to III.
        /// </summary>
        internal static string InterStagingSystemStageIII {
            get {
                return ResourceManager.GetString("InterStagingSystemStageIII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Admin/ManageClinician.aspx.
        /// </summary>
        internal static string ManageClinician {
            get {
                return ResourceManager.GetString("ManageClinician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Admin/ManageInstitute.aspx.
        /// </summary>
        internal static string ManageInstitute {
            get {
                return ResourceManager.GetString("ManageInstitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/ManagePSA.aspx.
        /// </summary>
        internal static string ManagePSA {
            get {
                return ResourceManager.GetString("ManagePSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Admin/ManageStudy.aspx.
        /// </summary>
        internal static string ManageStudy {
            get {
                return ResourceManager.GetString("ManageStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicare.
        /// </summary>
        internal static string Medicare {
            get {
                return ResourceManager.GetString("Medicare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login attempt was not successful. Please contact system administrator..
        /// </summary>
        internal static string MessageAccountInactive {
            get {
                return ResourceManager.GetString("MessageAccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login attempt was not successful. Please contact system administrator..
        /// </summary>
        internal static string MessageAccountLocked {
            get {
                return ResourceManager.GetString("MessageAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHI.
        /// </summary>
        internal static string NHI {
            get {
                return ResourceManager.GetString("NHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/OtherTreatment.aspx.
        /// </summary>
        internal static string OtherPage {
            get {
                return ResourceManager.GetString("OtherPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/PalliativeADTTherapy.aspx.
        /// </summary>
        internal static string PalyADTPage {
            get {
                return ResourceManager.GetString("PalyADTPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/PalliativRadiotherapy.aspx.
        /// </summary>
        internal static string PalyRTPage {
            get {
                return ResourceManager.GetString("PalyRTPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biclonal.
        /// </summary>
        internal static string ParaproteinTypeBiclonal {
            get {
                return ResourceManager.GetString("ParaproteinTypeBiclonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ig.
        /// </summary>
        internal static string ParaproteinTypesIg {
            get {
                return ResourceManager.GetString("ParaproteinTypesIg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/PatientList.aspx.
        /// </summary>
        internal static string PatentListPagePath {
            get {
                return ResourceManager.GetString("PatentListPagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/PatientAdmin.aspx.
        /// </summary>
        internal static string PatientPagePath {
            get {
                return ResourceManager.GetString("PatientPagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/Radiotherapy.aspx.
        /// </summary>
        internal static string RadiotherapyPage {
            get {
                return ResourceManager.GetString("RadiotherapyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/Review.aspx.
        /// </summary>
        internal static string ReviewEditPagePath {
            get {
                return ResourceManager.GetString("ReviewEditPagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Admin/Study.aspx.
        /// </summary>
        internal static string StudyEditPath {
            get {
                return ResourceManager.GetString("StudyEditPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/Surgery.aspx.
        /// </summary>
        internal static string SurgeryPage {
            get {
                return ResourceManager.GetString("SurgeryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/AlloSCT.aspx.
        /// </summary>
        internal static string TherapyAlloSCTPagePath {
            get {
                return ResourceManager.GetString("TherapyAlloSCTPagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/ASCT.aspx.
        /// </summary>
        internal static string TherapyASCTPagePath {
            get {
                return ResourceManager.GetString("TherapyASCTPagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/MaintenanceTherapy.aspx.
        /// </summary>
        internal static string TherapyMaintenancePagePath {
            get {
                return ResourceManager.GetString("TherapyMaintenancePagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/TURPTherapy.aspx.
        /// </summary>
        internal static string TURPPage {
            get {
                return ResourceManager.GetString("TURPPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Forms/WWAS.aspx.
        /// </summary>
        internal static string WWASPage {
            get {
                return ResourceManager.GetString("WWASPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
