<%@ Page Title="" Language="C#" MasterPageFile="~/Views/Shared/Site.Master" AutoEventWireup="True"
    CodeBehind="HealthMonitoring.aspx.cs" Inherits="WebApplication.Views.SYSADMIN.HealthMonitoring" %>

<asp:Content ID="Content2" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>

<asp:Content ID="Content4" ContentPlaceHolderID="MainContent" runat="server">
    <h2>Health Monitoring Log</h2>

    <form id="form1">
        <div>
            <p>
                The following log is generated by querying the aspnet_WebEvents_Events table directly.
            </p>
            <p>
                <asp:DetailsView ID="LogEntryDetails" runat="server" AutoGenerateRows="False" CellPadding="4"
                    DataKeyNames="EventId" DataSourceID="EventLogDetailsDataSource" EnableViewState="False"
                    ForeColor="#333333" GridLines="None">
                    <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
                    <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                    <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                    <Fields>
                        <asp:BoundField DataField="EventId" HeaderText="EventId" ReadOnly="True" SortExpression="EventId" />
                        <asp:BoundField DataField="EventTimeUtc" HeaderText="EventTimeUtc" SortExpression="EventTimeUtc" />
                        <asp:BoundField DataField="EventTime" HeaderText="EventTime" SortExpression="EventTime" />
                        <asp:BoundField DataField="EventType" HeaderText="EventType" SortExpression="EventType" />
                        <asp:BoundField DataField="EventSequence" HeaderText="EventSequence" SortExpression="EventSequence" />
                        <asp:BoundField DataField="EventOccurrence" HeaderText="EventOccurrence" SortExpression="EventOccurrence" />
                        <asp:BoundField DataField="EventCode" HeaderText="EventCode" SortExpression="EventCode" />
                        <asp:BoundField DataField="EventDetailCode" HeaderText="EventDetailCode" SortExpression="EventDetailCode" />
                        <asp:BoundField DataField="Message" HeaderText="Message" SortExpression="Message" />
                        <asp:BoundField DataField="ApplicationPath" HeaderText="ApplicationPath" SortExpression="ApplicationPath" />
                        <asp:BoundField DataField="ApplicationVirtualPath" HeaderText="ApplicationVirtualPath" SortExpression="ApplicationVirtualPath" />
                        <asp:BoundField DataField="MachineName" HeaderText="MachineName" SortExpression="MachineName" />
                        <asp:BoundField DataField="RequestUrl" HeaderText="RequestUrl" SortExpression="RequestUrl" />
                        <asp:BoundField DataField="ExceptionType" HeaderText="ExceptionType" SortExpression="ExceptionType" />
                        <asp:BoundField DataField="Details" HeaderText="Details" SortExpression="Details" />
                    </Fields>
                    <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" />
                    <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <AlternatingRowStyle BackColor="White" />
                </asp:DetailsView>

                <asp:SqlDataSource ID="EventLogDetailsDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ApplicationServices %>"
                    SelectCommand="SELECT EventId, EventTimeUtc, EventTime, EventType, EventSequence, EventOccurrence, EventCode, EventDetailCode, Message, ApplicationPath, ApplicationVirtualPath, MachineName, RequestUrl, ExceptionType, Details FROM aspnet_WebEvent_Events WHERE (EventId = @EventId)">
                    <SelectParameters>
                        <asp:ControlParameter ControlID="EventLog" Name="EventId" PropertyName="SelectedValue" />
                    </SelectParameters>
                </asp:SqlDataSource>
            </p>
            <p>
                <asp:GridView ID="EventLog" runat="server" AllowPaging="True" AllowSorting="True"
                    AutoGenerateColumns="False" CellPadding="4" DataKeyNames="EventId" DataSourceID="EventLogDataSource"
                    ForeColor="#333333" GridLines="None" PageSize="30">
                    <EmptyDataTemplate>
                        There is no events in the event log currently.
                    </EmptyDataTemplate>
                    <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <Columns>
                        <asp:CommandField SelectText="Details" ShowSelectButton="True" />
                        <asp:BoundField DataField="EventTime" HeaderText="Time" SortExpression="EventTime" />
                        <asp:BoundField DataField="EventCode" HeaderText="Code" SortExpression="EventCode" />
                        <asp:BoundField DataField="Message" HeaderText="Message" SortExpression="Message" />
                        <asp:BoundField DataField="RequestUrl" HeaderText="Url" SortExpression="RequestUrl" />
                    </Columns>
                    <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                    <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                    <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <AlternatingRowStyle BackColor="White" />
                </asp:GridView>

                <asp:SqlDataSource ID="EventLogDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ApplicationServices %>"
                    SelectCommand="SELECT * FROM aspnet_WebEvent_Events ORDER BY EventTime DESC"></asp:SqlDataSource>
            </p>
            <p>
                <asp:Button ID="ClearDataButton" runat="server" Text="Clear Health Monitoring Data"
                    CausesValidation="false" OnClick="ClearDataClicked" ToolTip="Reset password" OnClientClick="javascript:return confirm('Are you sure you want to delete all health monitoring data?')" />
            </p>
        </div>
    </form>
</asp:Content>
