//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Site_Audit
    {
        public string Action { get; set; }
        public string AuditUserName { get; set; }
        public System.DateTime AuditDate { get; set; }
        public int SiteId { get; set; }
        public string HPIO { get; set; }
        public string SiteName { get; set; }
        public string SiteRoleName { get; set; }
        public string SitePrimaryContact { get; set; }
        public string SitePh1 { get; set; }
        public string SiteSecondaryContact { get; set; }
        public string SitePh2 { get; set; }
        public string SiteAddr { get; set; }
        public string SiteSuburb { get; set; }
        public Nullable<int> SiteStateId { get; set; }
        public string SitePcode { get; set; }
        public Nullable<int> SiteCountryId { get; set; }
        public Nullable<int> SiteTypeId { get; set; }
        public Nullable<int> SiteStatusId { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedByDateTime { get; set; }
        public Nullable<System.DateTime> EAD { get; set; }
    }
}
