//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PatientComplications
    {
        public int Id { get; set; }
        public Nullable<int> FuId { get; set; }
        public Nullable<int> ComplicationId { get; set; }
        public Nullable<int> OpId { get; set; }
    
        public virtual tbl_Complications tbl_Complications { get; set; }
        public virtual tbl_FollowUp tbl_FollowUp { get; set; }
        public virtual tbl_PatientOperation tbl_PatientOperation { get; set; }
        public virtual tlkp_Complications tlkp_Complications { get; set; }
    }
}
