//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Device
    {
        public tbl_Device()
        {
            this.tbl_UserFavouriteDeviceDetails = new HashSet<tbl_UserFavouriteDeviceDetails>();
        }
    
        public int DeviceId { get; set; }
        public string DeviceModel { get; set; }
        public Nullable<int> DeviceBrandId { get; set; }
        public string DeviceDescription { get; set; }
        public Nullable<int> IsDeviceActive { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    
        public virtual tbl_DeviceBrand tbl_DeviceBrand { get; set; }
        public virtual ICollection<tbl_UserFavouriteDeviceDetails> tbl_UserFavouriteDeviceDetails { get; set; }
    }
}
