//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FollowUp
    {
        public tbl_FollowUp()
        {
            this.tbl_PatientComplications = new HashSet<tbl_PatientComplications>();
            this.tbl_FollowUpCall = new HashSet<tbl_FollowUpCall>();
        }
    
        public int FUId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> OperationId { get; set; }
        public Nullable<System.DateTime> FUDate { get; set; }
        public Nullable<int> AttmptCallId { get; set; }
        public Nullable<bool> SelfRptWt { get; set; }
        public Nullable<int> FUVal { get; set; }
        public Nullable<int> FUPeriodId { get; set; }
        public Nullable<bool> BSR_to_Follow_Up { get; set; }
        public string BSR_to_Follow_Up_Reason { get; set; }
        public Nullable<bool> LTFU { get; set; }
        public Nullable<System.DateTime> LTFUDate { get; set; }
        public Nullable<decimal> FUWt { get; set; }
        public Nullable<decimal> FUBMI { get; set; }
        public Nullable<bool> PatientFollowUpNotKnown { get; set; }
        public Nullable<bool> SEId1 { get; set; }
        public Nullable<bool> SEId2 { get; set; }
        public Nullable<bool> SEId3 { get; set; }
        public string ReasonOther { get; set; }
        public Nullable<int> DiabStatId { get; set; }
        public Nullable<int> DiabRxId { get; set; }
        public Nullable<int> ReOpStatId { get; set; }
        public Nullable<int> FurtherInfoSlip { get; set; }
        public Nullable<int> FurtherInfoPort { get; set; }
        public string Othinfo { get; set; }
        public Nullable<int> EmailSentToSurg { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string BatchUpdateReason { get; set; }
        public Nullable<int> OpBowelObsID { get; set; }
    
        public virtual tbl_PatientOperation tbl_PatientOperation { get; set; }
        public virtual tlkp_AttemptedCalls tlkp_AttemptedCalls { get; set; }
        public virtual tlkp_DiabetesTreatment tlkp_DiabetesTreatment { get; set; }
        public virtual tlkp_FollowUpPeriod tlkp_FollowUpPeriod { get; set; }
        public virtual tlkp_ReasonPort tlkp_ReasonPort { get; set; }
        public virtual tlkp_ReasonSlip tlkp_ReasonSlip { get; set; }
        public virtual tlkp_YesNo tlkp_YesNo { get; set; }
        public virtual ICollection<tbl_PatientComplications> tbl_PatientComplications { get; set; }
        public virtual ICollection<tbl_FollowUpCall> tbl_FollowUpCall { get; set; }
        public virtual tbl_Patient tbl_Patient { get; set; }
    }
}
