//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserFavouriteDeviceDetails_Audit
    {
        public string Action { get; set; }
        public string AuditUserName { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<int> FavDevId { get; set; }
        public Nullable<int> SurgId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> OpStatus { get; set; }
        public Nullable<int> OpType { get; set; }
        public Nullable<int> OpRevType { get; set; }
        public Nullable<int> DevId { get; set; }
        public Nullable<int> DevType { get; set; }
        public Nullable<int> DevBrand { get; set; }
        public Nullable<int> DevManuf { get; set; }
        public Nullable<bool> PriPortRet { get; set; }
        public Nullable<int> DevPortMethId { get; set; }
        public int ButtressID { get; set; }
        public Nullable<int> ButtTypeID { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ParentFavDevId { get; set; }
    }
}
