//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FollowUp_Audit
    {
        public string Action { get; set; }
        public string AuditUserName { get; set; }
        public System.DateTime AuditDate { get; set; }
        public int FUId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> OperationId { get; set; }
        public Nullable<System.DateTime> FUDate { get; set; }
        public Nullable<int> AttmptCallId { get; set; }
        public Nullable<bool> SelfRptWt { get; set; }
        public Nullable<int> FUVal { get; set; }
        public Nullable<int> FUPeriodId { get; set; }
        public Nullable<bool> BSR_to_Follow_Up { get; set; }
        public string BSR_to_Follow_Up_Reason { get; set; }
        public Nullable<bool> LTFU { get; set; }
        public Nullable<System.DateTime> LTFUDate { get; set; }
        public Nullable<decimal> FUWt { get; set; }
        public Nullable<decimal> FUBMI { get; set; }
        public Nullable<bool> PatientFollowUpNotKnown { get; set; }
        public Nullable<bool> SEId1 { get; set; }
        public Nullable<bool> SEId2 { get; set; }
        public Nullable<bool> SEId3 { get; set; }
        public string ReasonOther { get; set; }
        public Nullable<int> DiabStatId { get; set; }
        public Nullable<int> DiabRxId { get; set; }
        public Nullable<int> ReOpStatId { get; set; }
        public Nullable<int> FurtherInfoSlip { get; set; }
        public Nullable<int> FurtherInfoPort { get; set; }
        public string Othinfo { get; set; }
        public Nullable<int> EmailSentToSurg { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string BatchUpdateReason { get; set; }
        public Nullable<int> OpBowelObsID { get; set; }
    }
}
