//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tlkp_OperationStatus
    {
        public tlkp_OperationStatus()
        {
            this.tbl_PatientOperation = new HashSet<tbl_PatientOperation>();
            this.tbl_UserFavouriteDeviceDetails = new HashSet<tbl_UserFavouriteDeviceDetails>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tbl_PatientOperation> tbl_PatientOperation { get; set; }
        public virtual ICollection<tbl_UserFavouriteDeviceDetails> tbl_UserFavouriteDeviceDetails { get; set; }
    }
}
