//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tlkp_SiteType
    {
        public tlkp_SiteType()
        {
            this.tbl_Site = new HashSet<tbl_Site>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tbl_Site> tbl_Site { get; set; }
    }
}
