//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tlkp_YesNo
    {
        public tlkp_YesNo()
        {
            this.tbl_FollowUp = new HashSet<tbl_FollowUp>();
            this.tbl_PatientOperation = new HashSet<tbl_PatientOperation>();
            this.tbl_PatientOperation1 = new HashSet<tbl_PatientOperation>();
            this.tbl_PatientOperationDeviceDtls = new HashSet<tbl_PatientOperationDeviceDtls>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tbl_FollowUp> tbl_FollowUp { get; set; }
        public virtual ICollection<tbl_PatientOperation> tbl_PatientOperation { get; set; }
        public virtual ICollection<tbl_PatientOperation> tbl_PatientOperation1 { get; set; }
        public virtual ICollection<tbl_PatientOperationDeviceDtls> tbl_PatientOperationDeviceDtls { get; set; }
    }
}
