//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Business
{
    using System;
    
    public partial class ufn_Missing_DataList_Result1
    {
        public int FollowUpPeriodID { get; set; }
        public int OperationID { get; set; }
        public int Patient_ID { get; set; }
        public string Patient_FName { get; set; }
        public string Patient_LastName { get; set; }
        public string Patient_Gender { get; set; }
        public Nullable<System.DateTime> Operation_Date { get; set; }
        public string Surgeon { get; set; }
        public string Hospital { get; set; }
        public string Op_Form_Status { get; set; }
        public string Day_30 { get; set; }
        public string Year_1 { get; set; }
        public string Year_2 { get; set; }
        public string Year_3 { get; set; }
        public string Year_4 { get; set; }
        public string Year_5 { get; set; }
        public string Year_6 { get; set; }
        public string Year_7 { get; set; }
        public string Year_8 { get; set; }
        public string Year_9 { get; set; }
        public string Year_10 { get; set; }
    }
}
